name: Update Pipelines Status Pending

description: Notifies pipeline status pending

inputs:
  step-command:
    description: 'Name of workflow command'
    required: true
    default: ''

runs:
  using: composite
  steps:
      - name: "Update GitHub Status for pending"
        if: github.event_name == 'repository_dispatch'
        uses: docker://cloudposse/github-status-updater
        with:
          args: "-action update_state -state pending -ref ${{ env.REPO_SHA }} -repo ${{ env.REPO_NAME }}"
        env:
          REPO_SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
          REPO_NAME: ${{ github.event.client_payload.github.payload.repository.name || github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_CONTEXT: "${{ inputs.step-command }} (${{ github.event_name }})"
          GITHUB_DESCRIPTION: "started by @${{ github.event.client_payload.github.actor || github.actor }}"
          GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
          GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login || github.repository_owner }}
