name: Setup Tests for IaC

description: Checks out the code, sets up caches, pulls/saves/loads docker build harness image.

runs:
  using: composite
  steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Init gopath cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/.cache/go"
        key: "gopath|${{ hashFiles('.tool-versions') }}|${{ hashFiles('go.sum') }}"

    - name: Init gobuild cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/.cache/go-build"
        key: "gobuild|${{ hashFiles('.tool-versions') }}|${{ hashFiles('go.sum') }}"

    - name: Init docker cache
      id: init-docker-cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/.cache/docker"
        key: "docker|${{ hashFiles('Makefile') }}"

    - name: Docker save build harness
      if: steps.init-docker-cache.outputs.cache-hit != 'true'
      run: |
        make docker-save-build-harness

    - name: Load build harness
      run: |
        make docker-load-build-harness
