# Attribution for a bunch of this goes to CloudPosse
# https://github.com/cloudposse/actions/blob/master/.github/workflows/test-command.yml

name: test
on:
  repository_dispatch:
    types: [test-command]
  pull_request:
    paths:
      - "**.tf"
      - "**.go"

  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  # Parse the command so we can decide which tests to run. Examples: "/test all", "/test validate", "/test e2e"
  # We can do as many of these as we want to get as granular as we want.
  parse:
    runs-on: ubuntu-latest
    outputs:
      run-build: ${{ steps.parse.outputs.build }}
      run-e2e: ${{ steps.parse.outputs.e2e }}
    steps:
      - name: Parse Args
        id: parse
        env:
          DEBUG: ${{ toJSON(github.event.client_payload.slash_command) }}
          ARGS_V1: ${{ github.event.client_payload.slash_command.arg1 }}
          ARGS_V2: ${{ github.event.client_payload.slash_command.args.unnamed.all }}
          EVENT_NAME: ${{ github.event_name }}
        shell: bash
        run: |
          ARGS="${ARGS_V1}${ARGS_V2}"
          # set ARGS to "all" if EVENT_NAME is "push"
          if [[ "${EVENT_NAME}" == "push" ]]; then
              ARGS="all"
          fi
          printf "Event name is %s\n" "$EVENT_NAME"
          printf "Args are %s\n" "$ARGS"
          printf "\n\nslash_command is %s\n\n" "$DEBUG"
          COMMANDS=(E2E)
          if printf "%s" "${ARGS^^}" | grep -qE '\bALL\b'; then
            # "all" explicitly does not include "ping"
            for cmd in "${COMMANDS[@]}"; do
              [[ $cmd == "PING" ]] && ! { printf "%s" "${ARGS^^}" | grep -qE '\bPING\b'; } && continue
              printf -v "$cmd" "true"
            done
          else
            for cmd in "${COMMANDS[@]}"; do
              if printf "%s" "${ARGS^^}" | grep -qE "\b${cmd}\b"; then
                printf -v "$cmd" "true"
              fi
            done
          fi
          for out in "${COMMANDS[@]}"; do
            printf "::set-output name=%s::%s\n" "${out,,}" "${!out:-false}"
            printf "%s=%s\n" "${out,,}" "${!out:-false}"
          done

  # Run the E2E tests
  e2e:
    runs-on: ubuntu-latest
    needs: parse
    if: needs.parse.outputs.run-e2e == 'true'
    steps:

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Initialize Pipeline
        uses: ./.github/actions/init-pipeline

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-east-1

      - name: Run E2E tests
        env:
          REPO_URL: https://github.com/${{ github.repository }}.git
          GIT_BRANCH: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
        run: |
          make test
